name: Trigger the 'pactum-pruebas-2' Test Workflow on Testkube

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: kubeshop/setup-testkube@v1
      with:
        organization: tkcorg_8f77df7a24461b2e
        environment: tkcenv_d6606793d0488ee0
        token: ${{ secrets.TK_API_TOKEN }}
    - run: |
        testkube run testworkflow pactum-pruebas-2 -f
    
