name: Trigger the 'pactum-pruebas-2' Test Workflow on Testkube

on:
  pull_request:
    branches: [main]

jobs:
  print-token:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ secrets.TK_TOKEN_API }}
    steps:
      - name: Print token api
        run: echo $MY_ENV_VAR
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: kubeshop/setup-testkube@v1
      with:
        organization: tkcorg_8f77df7a24461b2e
        environment: tkcenv_d6606793d0488ee0
        token: ${{ secrets.TK_TOKEN_API }}
    - run: |
        testkube run testworkflow pactum-pruebas-2 -f
    
